  Algoritmo "verificaidade"
Var
idade: inteiro
nome: caracter
Inicio
Escreva ("Digite o nome:")
Leia (nome)
Escreva ("Digite a idade:")
Leia (idade)
Se (idade >= 65) entao
Escreva (nome, " sua idade é ",idade, ", Sr(a) ja é Idoso!!")
Senao
Se (idade < 18) entao
Escreva (nome," sua idade é ",idade, ", você é menor de idade!!")
Senao
Escreva (nome," sua idade é ",idade, ", você é maior de idade!!")
Fimse
Fimse
Fimalgoritmo
